name: admin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  firebase_core: ^2.27.0
  firebase_storage: ^11.6.9
  flutter:
    sdk: flutter
  flutter_image_slideshow: ^0.1.6
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  get: 4.6.6
  google_fonts: ^4.0.4
  horizontal_card_pager: ^1.1.1
  image_picker: ^1.0.7
  loading_animation_widget: ^1.2.1
  motion_toast: ^2.8.0
  pretty_dio_logger: ^1.3.1
  quickalert: ^1.1.0
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
