// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6rgnxrkJbeU3XbEWb2uLE9_vyyOu_ZEg',
    appId: '1:353166599912:web:40746dcadbe2e145e04b5d',
    messagingSenderId: '353166599912',
    projectId: 'e-commerce-de666',
    authDomain: 'e-commerce-de666.firebaseapp.com',
    storageBucket: 'e-commerce-de666.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM-FUT8yUi-g00yZ8X_Fm_xGVSWCwP2Fg',
    appId: '1:353166599912:android:b849f3ce07cac5cfe04b5d',
    messagingSenderId: '353166599912',
    projectId: 'e-commerce-de666',
    storageBucket: 'e-commerce-de666.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOCMRsk4InM0E2gX6TXa5cJh8QZKcCeKs',
    appId: '1:353166599912:ios:7415f6be16c2e23ae04b5d',
    messagingSenderId: '353166599912',
    projectId: 'e-commerce-de666',
    storageBucket: 'e-commerce-de666.appspot.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOCMRsk4InM0E2gX6TXa5cJh8QZKcCeKs',
    appId: '1:353166599912:ios:b16f3620065da04de04b5d',
    messagingSenderId: '353166599912',
    projectId: 'e-commerce-de666',
    storageBucket: 'e-commerce-de666.appspot.com',
    iosBundleId: 'com.example.admin.RunnerTests',
  );
}
